name: Java CI with Maven

on:
  push:
    branches:
      - '*'  # Der Workflow wird nur ausgeführt, wenn du auf den `main`-Branch pusht

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
